### PR TITLE
Update publisher to EBMS VF

### PR DESCRIPTION
**Pull request by timothy22000**
Added new EBMS VF publisher as the spec had old publisher. Need to discuss with tom on how to handle old RedbeeBDS publisher

### CODE REVIEW

**Comment by Dalamar42** [comment]
Has the previous version of this publisher been released? I don't think you can change a publisher after it has already been released without causing issues.

**Comment by timothy22000** [comment]
Yeah it has been released but nothing redbee related is ingested on production yet. On the other hand, stage database has this publisher. What would be the way to change the publisher? Do I need to remint stage somehow?

**Comment by Dalamar42** [comment]
Once this publisher has been released then the next time *any* key is modified by the admin page the new publisher will have been written to the db under that key making it very hard to change. Do you need to change this?

Also keep in mind there is no such thing as releasing a publisher only to stage. Stage admin is fed by Deer prod so publishers are always released to both stage and prod at the same time.

**Comment by timothy22000** [comment]
Yeap, I have to change this since chris wants this new publisher rather than the one on the spec.

Ah got it. Then, What should I do to change the publisher?

**Comment by Dalamar42** [comment]
This is a high risk change. I'm not sure what the steps are. For now I'd add a new publisher and have a chat with Tom tomorrow about removing the old one as a separate step.

Maybe we can just disable the old one rather than remove it

**Comment by timothy22000** [comment]
Alright =b.

**Comment by tfm** [comment]
Leave the old one as-is. If it's no longer required, then mark as @deprecated, but the new ingest shouldn't affect the statutory ingest publisher.

**Comment by timothy22000** [comment]
Got it. thanks :)

**Pull request merged**
